[package]
name = "avian_rerecast"
description = "TODO"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
readme = { workspace = true }

[dependencies]
bevy = { workspace = true }
avian3d = { workspace = true }
slotmap = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
rerecast = { version = "0.0.1", path = "../rerecast", features = ["bevy"] }

# Editor integration
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
bevy_rerecast = { version = "0.0.1", path = "../bevy_rerecast" }
bevy_rerecast_transmission = { version = "0.0.1", path = "../bevy_rerecast_transmission", optional = true }

[features]
default = ["editor_integration"]
serialize = ["dep:serde", "avian3d/serialize", "rerecast/serialize"]
editor_integration = [
    "serialize",
    "dep:serde_json",
    "dep:bevy_rerecast_transmission",
    "bevy/bevy_remote",
]

[lints]
workspace = true
